### ISSUE TITLE
Stuck on "Download mode device found"

### ISSUE THREAD

**Issue by AymenKcm1** [palera1n/palen1x#1]
Hi, 

Thanks for creating this and making it easier to jailbreak with palera1n 😊

I don't know if this issue is supposed to be here or under palera1n GitHub, since I used palen1x I thought it should be here, anyway here it is (it's a lengthy explanation so bear with me 😅): 

I tried it on my iPad Pro 9.7" on iPadOS 15.1.1 : It worked the first try (yay!) 🙂

![image](https://user-images.githubusercontent.com/67245917/218370266-335dd015-7774-498e-8b09-6d1d31946b37.jpeg)

then I started installing tweaks (ofc after checking their compatibility first) and everything was good, 

![image](https://user-images.githubusercontent.com/67245917/218370286-a7f25124-9100-4775-a1c1-57dcf840813d.jpeg)

until I noticed that the palera1n app was gone from the springboard (maybe it's supposed to do that idk) 

so I tried to Rebuild Icon Cache with TrollStore (I had already installed before jailbreaking) and still it didn't show up again

I ignored it, and opened Sileo to continue installing tweaks but I had an issue with it: 
 - All repos were gone
 - No packages show in the packages page
 - Error: " Didn't find architectures "iphoneos-arm64" " when adding repos 

![image](https://user-images.githubusercontent.com/67245917/218370312-c92a1b59-0b28-4fef-87d7-da51e602c88e.jpeg)

So I tried to fix this by rebooting and rejailbreaking, palera1n app is back but the Sileo error still the same, installed tweaks still work but can't do anything in Sileo (adding repos / install or managing tweaks) 

I tried " Do all " in palera1n app but with no luck, re-installed the bootstrap and it didn't fix the issue, 

As a last resort I tried to restore rootFS with palen1x but it got stuck at " Download mode device found " and it stayed like that for over 30 min, 

![image](https://user-images.githubusercontent.com/67245917/218370447-97b11131-dc42-4006-9de8-ea4c39814038.jpeg)

I rebooted and tried to jailbreak again and same thing it gets stuck at that stage. 

I can boot the device in normal mode but can't re-enable the jailbreak or restore rootFS.

I hope there's a fix for this, I appreciate any help. 

Thanks in advance.

Keep up the good work 👍

**Comment by flowerible** [comment]
what arguments did you use when jailbreaking?

**Comment by AymenKcm1** [comment]
I didn't specify any arguments I first jailbreak successfully, and since palen1x auto-boots with -f -v arguments I didn't have to specify anything.

**Comment by flowerible** [comment]
Did you use anything else before trying to use palen1x? It looks like you have something completely different installed. Not saying you should do anything right now, just asking to make sure.

**Comment by AymenKcm1** [comment]
No, I didn't, 

I had this iPad updated with DelayOTA to iPadOS 15.1.1 when the window was still open, [I tried palera1n on Linux but it didn't work](https://twitter.com/aym3n_kcm/status/1593403833606197248?s=46&t=cW8bwMI3nPrPNs81N5z4vg), when I tried palen1x (palera1n-c) it worked from the first try.

Does the failed palera1n attempt have anything with this?

**Comment by flowerible** [comment]
It shouldn't, it looks like palera1n-c did something it shouldn't of have.

I assume you have trollstore installed, can you please refresh app registrations and install [this IPA](https://static.palera.in/artifacts/loader/universal/palera1n.ipa)?

This has a feature to remove rootless jailbreak contents in tools which is what it looked like what you installed [ `iphoneos-arm64` ]

**Comment by AymenKcm1** [comment]
Thanks, but it doesn't do anything.
Maybe it does but it's not showing verbose info?
What does it suppose to show after tapping Remove?

**Comment by AymenKcm1** [comment]
Update: 

I managed to rejailbreak again in rootful mode (default in palen1x) : 

![image](https://user-images.githubusercontent.com/67245917/218530782-cd419273-ebaf-4d59-b5b0-b04f4eefb512.jpeg)

![image](https://user-images.githubusercontent.com/67245917/218530836-57766984-b152-4b1a-9c5b-6065d3ed2be0.jpeg)

Palera1n app is installed, but nothing is working, so I tried reinstalling the bootstrap : 

![image](https://user-images.githubusercontent.com/67245917/218531057-1b18b9b2-28a8-4123-bf95-53353b0bda08.jpeg)

But no luck, still no packages : 

![image](https://user-images.githubusercontent.com/67245917/218531238-f5a6793e-972a-4890-b758-d73c36c0b26f.jpeg)

Or sources : 

![image](https://user-images.githubusercontent.com/67245917/218531287-a6675e49-7de0-446a-b4c3-b9b2f51cc521.jpeg)

When I try to add palera1n repo manually I get this error : 

![image](https://user-images.githubusercontent.com/67245917/218531417-a9cfed7e-2842-4d9e-94ce-fc165393c7f8.jpeg)

So I tried to restore rootFS 

![image](https://user-images.githubusercontent.com/67245917/218531656-6154ca57-5b4a-40e8-b717-5582222af6f8.jpeg)

And it's been over an hour stuck in " Download mode device found " stage : ![image](https://user-images.githubusercontent.com/67245917/218531870-deb55edb-b3ba-4811-8e3f-f65feee8c5d0.jpeg)

Is there another way to restore rootFS? 

Or a fix for the Sileo error " Didn't find architectures "iphoneos-arm64" " ?

**Comment by AymenKcm1** [comment]
Update (FIXED ✅) 

I was able to restore rootFS successfully and now everything is back working : 

Sources are back : 

![image](https://user-images.githubusercontent.com/67245917/218537481-cda90191-06ad-40a5-885b-c3f4c7939f2c.jpeg)

Packages are installed : 

![image](https://user-images.githubusercontent.com/67245917/218537528-e658fab1-4f2c-498e-8c83-92874fbbac08.jpeg)

Adding sources work and I can login to get my purchases : 

![image](https://user-images.githubusercontent.com/67245917/218537658-ee93a346-d301-46eb-aa90-752d2075eecf.jpeg)

![image](https://user-images.githubusercontent.com/67245917/218537682-f31de4c4-6156-4bc7-89ad-88941ab7b2a8.jpeg)

![image](https://user-images.githubusercontent.com/67245917/218537707-99f94f56-8bb6-4056-b0bd-a21bf65eb042.jpeg)

![image](https://user-images.githubusercontent.com/67245917/218537738-a513d7ef-354f-49cf-85be-d66c089d5100.jpeg)

And tweaks install works 👍

![image](https://user-images.githubusercontent.com/67245917/218537814-0c535b9d-62f4-4f91-9f51-d29715551678.jpeg)

![image](https://user-images.githubusercontent.com/67245917/218537844-6f3fe243-95c0-4a32-b8a7-39be35e1bfc5.jpeg)

I'm so glad I'm jailbroken again 🙂

![image](https://user-images.githubusercontent.com/67245917/218537938-65d96991-2e38-48bd-980d-2e89cd08bdc6.jpeg)

It just needed some patience and some luck I guess 😅

I hope this somehow help others if they had the same issue. 

Thanks.
