### ISSUE TITLE
Stuck At Booting

### ISSUE THREAD

**Issue by Grespy** [palera1n/palen1x#20]
I have an Iphone 7 plus 15,7,3... everything keeps working fine until the kernel installing thing reach booting... it stayed stuck there for like 20 mins and then i hard resetted the phone to open it :P

**Comment by 0xallie** [comment]
This is not a palen1x-specific issue, please go to https://discord.gg/palera1n for support.

Your issue is most likely that you forgot to enable the "Create FakeFS" (or "Create BindFS" if you're on a 16–32 GB device). You need to do that first and then run it again with those options disabled.
