### ISSUE TITLE
Rejailbreak broken

### ISSUE THREAD

**Issue by MagicDude17** [palera1n/palen1x#24]
Every time I shut my phone down and want to rejailbreak the Palera1n app disappears and my phone won’t boot in the jailbroken state. Issue started occurring after I jailbroke my phone with Palen1x version 1.0.8 and version 1.0.7 doesn’t want to recognize my usb and can’t connect to the phone.

**Comment by Gghuzr** [comment]
Similar issue on iPad Pro A10 device. On re-jailbreak with rootful mode the kernel booting starts but always hang on apple logo (could be reproduce x times). Only rootless mode works on re-Jailbreak.
The Only work around is to restore Root fs. 2.Recreating fakefs again and Then -f option under rootful Mode is complete kernel booting w/o Any issues.

**Comment by MagicDude17** [comment]
I found a fix. You just need to select safe mode from the palen1x arguments. And then you enable the tweaks from the palera1n loader app on your phone.
