### ISSUE TITLE
What devices can this run on?

### ISSUE THREAD

**Issue by adminy** [palera1n/palen1x#25]
Would I be able to run it on AudioOS / Homepod? or is it just m1 chips?

**Comment by eJzLyFRIKy0qykwtBgAUzQPy** [comment]
if you're talking about using the homepod/audioOS device to jailbreak another device, no. if you're talking about using a pc to jailbreak the homepod/audioOS device, that may come in the future as we have the patches needed. We have yet to implement the functionality, however.

**Comment by adminy** [comment]
a pc to jailbreak homepod OS. I'm not interested in the jailbreak as much as just ssh.

**Comment by plooshi** [comment]
if you're trying to run the jailbreak from the homepod to jailbreak another device, it is possible but there's really no point in doing it and need a jailbreak that patches platform check (checkra1n, etc). However, if you're trying to jailbreak the homepod using a computer, that will be possible in the future as the patches needed to make tvOS/audioOS etc work are implemented, however the ability to actually jailbreak them is not. We hope to implement it soon.

**Comment by adminy** [comment]
I am just worried that it won't work on the new s7 chip.

**Comment by plooshi** [comment]
if it's newer than 2018, it most likely will not work.

**Comment by adminy** [comment]
its january 2023 ... and here I was hoping I could see how apple implements thread ...
