### ISSUE TITLE
Palen1x keeps hanging at "Ignoring non-arm64 device..."

### ISSUE THREAD

**Issue by Marko2155** [palera1n/palen1x#26]
For some reason i plug the USB-C cable in and on the screen it shows
"Normal mode device connected
<Warning>Ignoring non-arm64 device..."
Then it hangs. I even leave it for a few minutes and nothing happens.

**Comment by 0xallie** [comment]
> The following devices are supported by palera1n on iOS 15.0–16.3.1:
> 
> iPhone 6s
> iPhone 6s Plus
> iPhone SE (2016)
> iPhone 7
> iPhone 7 Plus
> iPhone 8
> iPhone 8 Plus
> iPhone X
> 
> iPad mini 4
> iPad Air 2
> iPad (5th generation)
> iPad (6th generation)
> iPad (7th generation)
> iPad Pro (9.7")
> iPad Pro (12.9") (1st generation)
> iPad Pro (10.5")
> iPad Pro (12.9") (2nd generation)
> 
> iPod touch (7th generation)
> 
> This version list is FINAL. There will be NO updates to this list in terms of iOS/iPadOS devices. Support for tvOS/bridgeOS/audioOS may come in the future.
