### ISSUE TITLE
FakeFS doesn't create

### ISSUE THREAD

**Issue by iEnderman55** [palera1n/palen1x#29]
Please see this video for understanding better: https://youtu.be/w8ckbhhfqJA

**Comment by namdevel** [comment]
same, but i use palera1n in linux CLI

**Comment by Phongvngg1** [comment]
if you booted from virtual disk, you had better boot palen1x in hard disk, palera1n needs like 1gb for creating

**Comment by iEnderman55** [comment]
In fact I have used a normal computer, not a Virtual Machine

**Comment by namdevel** [comment]
still not working, and got stuck in pongo OS bot , after each minute then booting in IOs but Palera1n loader is none
