### ISSUE TITLE
iOS 16.4

### ISSUE THREAD

**Issue by orangetreefrog4** [palera1n/palen1x#32]
I'm not sure whether palen1x supports iOS 16 in the public beta yet. Could someone just tell me if it is?

**Comment by 0x6ff** [comment]
16.4 is not a public beta anymore. If you mean 16.5, iirc it is not currently supported but 16.4-16.4.1 are since palera1n 2.0.0~beta6/palen1x 1.0.9.

**Comment by orangetreefrog4** [comment]
Ok, thank you!

**Comment by plooshi** [comment]
16.5 is supported i think
