### ISSUE TITLE
cydia

### ISSUE THREAD

**Issue by snkdonkey** [palera1n/palen1x#7]
is there anyway to install cydia? looked everywhere and no luck

**Comment by TheMasterOfMike** [comment]
not via palen1x and not via palera1n loader.

I have to be honest, there really isn’t a point to Cydia anyways - it has issues on iOS 15+ not to mention that repositories no longer support paid packages there **and** that Sileo does everything Cydia can, but better.

**Comment by sasa8810** [comment]
> not via palen1x and not via palera1n loader.
> 
> I have to be honest, there really isn’t a point to Cydia anyways - it has issues on iOS 15+ not to mention that repositories no longer support paid packages there **and** that Sileo does everything Cydia can, but better.

It’s not true sileo can’t force remove package

**Comment by asdfugil** [comment]
it does work on some repositories again if X-Firmware header is 14.999
