### ISSUE TITLE
Jailbreak problem

### ISSUE THREAD

**Issue by Adunka** [palera1n/palen1x#8]
When I go into jailbreak and want to flash my phone, I get a message (ignoring non-arm64 device) but my operating system is 64 bit

**Comment by BigBoiMan123** [comment]
You are trying to jailbreak a device that is not and will never be compatible with palera1n.

**Comment by Adunka** [comment]
but it is iphone 14 pro

**Comment by flowerible** [comment]
iPhone 14 Pro is not supported.

**Comment by Adunka** [comment]
or can you please advise how to change IMEI address on iPhone？

**Comment by BigBoiMan123** [comment]
not possible

**Comment by Adunka** [comment]
thanks

**Comment by 0xallie** [comment]
You can't, it's burned into the baseband chip.
